config/routes.rb
Indigenius::Application.routes.draw do
  get "aboutus/index"

  get "aboutus/why_indigenius"

  get "aboutus/our_story"
 
  get "aboutus/clientele"

  get "aboutus/commitment"

  get "casestudies/index"

  get "casestudies/online_exam_framework"

  get "solutions/index"

  get "solutions/content_manage"
 
  get "solutions/test_genius"
  
  get "solutions/equilab"

  get "technologies/index"

  get "service/index"

  get "service/sharepoint_services"

  get "service/webapplication_development"

  get "service/product_development"

  get "service/opensource_customizations"

  get "service/staff_augmentation"

  get "service/reselling"

  resources :testimonials

  resources :news do
    get 'new_index' , :on => :collection 
  end

  get "dashboard/index"

resources :administrator

 resources :login do
 get 'logout' , :on => :collection
end
   get "home/index"
 
   get "home/careers"

   get "home/contact_us"

   get "home/sitemap"

   get "home/disclaimer"

   get "home/privacy_policy"

   get "home/about_us"

   get "home/feedback"

   post "home/process_email"

   root :to => "home#index"

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/testimonials.rb
class Testimonials < ActiveRecord::Base
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
    @latest_testimonial = Testimonials.last
  end
  def why_indigenius
    @latest_testimonial = Testimonials.last
  end
  def our_story
    @latest_testimonial = Testimonials.last
  end
  def clientele
    @latest_testimonial = Testimonials.last
  end
  def commitment
    @latest_testimonial = Testimonials.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
 def check_session
    if session[:admin].nil?
      flash[:error] = "You are not authenticated"
      redirect_to home_index_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :check_session 
 
  def index
    render :layout => 'admin' 
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @latest_news = News.last
     @latest_testimonial = Testimonials.last
  end 
  def careers
    @latest_testimonial = Testimonials.last
  end
  def contact_us
    @latest_testimonial = Testimonials.last
  end
  def sitemap
     @latest_testimonial = Testimonials.last
  end
  def disclaimer
     @latest_testimonial = Testimonials.last
  end
  def privacy_policy
     @latest_testimonial = Testimonials.last
  end
  def about_us
     @latest_testimonial = Testimonials.last
  end
  def feedback 
     @latest_testimonial = Testimonials.last
  end

  def process_email
   # puts '111111111111111111111111', params[:email]
    UserMailer.send_email(params[:email]).deliver
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  layout nil 

 def new    
    @administrator = Administrator.new
  end

 def create
 
   @administrator = Administrator.new(params[:administrator])
   @admin = Administrator.find_all_by_username(@administrator.username)
   if(!@admin.blank? && @admin.first.password.eql?(@administrator.password))
    session[:admin] = @admin.first.id
    flash[:notice] = "Logged in Successfully"
    redirect_to dashboard_index_path
   else
    flash[:error] = "Failed to login"
    redirect_to new_login_path
   end

  end


  def logout   
   session[:admin] = nil if session[:admin]   
   redirect_to new_login_path
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
 
 before_filter :check_session , :except => :new_index
layout :choose_layout
# layout 'admin' , :except => :new_index

#layout 'application' , :only => :new_index

  def index
    @news=News.all
    #respond_to do |format|
     # format.html 
  #end
  end

  def new
    @news = News.new
    #respond_to do |format|
     # format.html 
  #end
  end

  def create
    @news = News.new(params[:news])
    respond_to do |format|
      if @news.save
        format.html { redirect_to(@news, :notice => 'Update was successfully created.') }
       else
        format.html { render :action => "new" }
     end
  end
  end

  def edit
   @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to(news_index_path, :notice => 'Update was successfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    #respond_to do |format|
     # format.html { redirect_to(news_index_path) }   
  #end
end

  def show
   @news = News.find(params[:id])
   #respond_to do |format|
    #  format.html
 #end
 end
 def new_index
   @latest_testimonial = Testimonials.last
   @latest_news = News.all
 end
private
def choose_layout
puts 'ssssssssssssss'
if params[:action] == "new_index"
  'application'
else
  'admin'
end
end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def index
   @latest_testimonial = Testimonials.last
  end
  def sharepoint_services
   @latest_testimonial = Testimonials.last
  end
  def webapplication_development
   @latest_testimonial = Testimonials.last
  end
  def product_development
   @latest_testimonial = Testimonials.last
  end
  def opensource_customizations
   @latest_testimonial = Testimonials.last
  end
  def staff_augmentation
   @latest_testimonial = Testimonials.last
  end
  def reselling
   @latest_testimonial = Testimonials.last
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def index
    @latest_testimonial = Testimonials.last
  end
  def content_manage
    @latest_testimonial = Testimonials.last
  end
  def test_genius
    @latest_testimonial = Testimonials.last
  end
  def equilab
    @latest_testimonial = Testimonials.last
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f|%>
  <%= f.label :Content %>
  <%= f.text_field :content %><br/>

  <%= f.submit  %><br /></br />
<% end %>

app/views/news/edit.html.erb
<div id='content'>
  <div id='content-inner'>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

</div></div>

app/views/news/index.html.erb
<div id='content'>
  <div id='content-inner'>

<h1>Listing News And Updates</h1>

<table >
  <tr>
    <th align="left"><h4>Content</h4></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.content %></td>
    <td><%= link_to 'Show', news %></td>
    <td><%= link_to 'Edit', edit_news_path(news) %></td>
    <td><%= link_to 'Destroy', news, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Update', new_news_path %>
</div></div>

app/views/news/new.html.erb
<div id='content'>
  <div id='content-inner'>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>
</div></div>

app/views/news/new_index.html.erb
<div id="banner">
<div id="banner-inner">
<%= image_tag 'News_updates.png' , :alt => 'Indigenius Updates' , :title => 'Indigenius' %>
</div>
</div>
<div id="container">
  <div id="container-left">
 <h4>The News and Update Content Here</h4>
<% @latest_news.each do |item| %>
   <%= item.content %><br /><br />
<% end %>
  </div>
<div id="container-right">
<h4>Relevant Links </h4>
<%= link_to 'MS SharePoint Services' , service_sharepoint_services_path%><br />
<%= link_to 'Web Application Development' , service_webapplication_development_path%><br />
<%= link_to 'Outsourced Product Development' , service_product_development_path%><br />
<%= link_to 'OpenSource Customizations' , service_opensource_customizations_path %><br />
<%= link_to 'Value-added Staff Augmentation' , service_staff_augmentation_path %><br />
<%= link_to 'Value-added Reselling' , service_reselling_path %> | <%= params[:action] %><br />
<h4>A Word From Our Client</h4> 
<%= @latest_testimonial.clientword %>
<%= render 'layouts/mail_form' %>
</div>
</div>

app/views/news/show.html.erb
<div id='content'>
  <div id='content-inner'>
 <b>Content : </b>
 <%= @news.content %>
<%= link_to 'Edit', edit_news_path(@student) %> |
<%= link_to 'Back', news_index_path %>
</div></div>