config/routes.rb
Indigenius::Application.routes.draw do
  get "aboutus/index"

  get "aboutus/why_indigenius"

  get "aboutus/our_story"
 
  get "aboutus/clientele"

  get "aboutus/commitment"

  get "casestudies/index"

  get "casestudies/online_exam_framework"

  get "solutions/index"

  get "solutions/content_manage"
 
  get "solutions/test_genius"
  
  get "solutions/equilab"

  get "technologies/index"

  get "service/index"

  get "service/sharepoint_services"

  get "service/webapplication_development"

  get "service/product_development"

  get "service/opensource_customizations"

  get "service/staff_augmentation"

  get "service/reselling"

  resources :testimonials

  resources :news do
    get 'new_index' , :on => :collection 
  end

  get "dashboard/index"

resources :administrator

 resources :login do
 get 'logout' , :on => :collection
end
   get "home/index"
 
   get "home/careers"

   get "home/contact_us"

   get "home/sitemap"

   get "home/disclaimer"

   get "home/privacy_policy"

   get "home/about_us"

   get "home/feedback"

   post "home/process_email"

   root :to => "home#index"

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/testimonials.rb
class Testimonials < ActiveRecord::Base
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
    @latest_testimonial = Testimonials.last
  end
  def why_indigenius
    @latest_testimonial = Testimonials.last
  end
  def our_story
    @latest_testimonial = Testimonials.last
  end
  def clientele
    @latest_testimonial = Testimonials.last
  end
  def commitment
    @latest_testimonial = Testimonials.last
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :check_session 
 
  def index
    render :layout => 'admin' 
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @latest_news = News.last
     @latest_testimonial = Testimonials.last
  end 
  def careers
    @latest_testimonial = Testimonials.last
  end
  def contact_us
    @latest_testimonial = Testimonials.last
  end
  def sitemap
     @latest_testimonial = Testimonials.last
  end
  def disclaimer
     @latest_testimonial = Testimonials.last
  end
  def privacy_policy
     @latest_testimonial = Testimonials.last
  end
  def about_us
     @latest_testimonial = Testimonials.last
  end
  def feedback 
     @latest_testimonial = Testimonials.last
  end

  def process_email
   # puts '111111111111111111111111', params[:email]
    UserMailer.send_email(params[:email]).deliver
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  layout nil 

 def new    
    @administrator = Administrator.new
  end

 def create
 
   @administrator = Administrator.new(params[:administrator])
   @admin = Administrator.find_all_by_username(@administrator.username)
   if(!@admin.blank? && @admin.first.password.eql?(@administrator.password))
    session[:admin] = @admin.first.id
    flash[:notice] = "Logged in Successfully"
    redirect_to dashboard_index_path
   else
    flash[:error] = "Failed to login"
    redirect_to new_login_path
   end

  end


  def logout   
   session[:admin] = nil if session[:admin]   
   redirect_to new_login_path
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
 
 before_filter :check_session , :except => :new_index
layout :choose_layout
# layout 'admin' , :except => :new_index

#layout 'application' , :only => :new_index

  def index
    @news=News.all
    #respond_to do |format|
     # format.html 
  #end
  end

  def new
    @news = News.new
    #respond_to do |format|
     # format.html 
  #end
  end

  def create
    @news = News.new(params[:news])
    respond_to do |format|
      if @news.save
        format.html { redirect_to(@news, :notice => 'Update was successfully created.') }
       else
        format.html { render :action => "new" }
     end
  end
  end

  def edit
   @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to(news_index_path, :notice => 'Update was successfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    #respond_to do |format|
     # format.html { redirect_to(news_index_path) }   
  #end
end

  def show
   @news = News.find(params[:id])
   #respond_to do |format|
    #  format.html
 #end
 end
 def new_index
   @latest_testimonial = Testimonials.last
   @latest_news = News.all
 end
private
def choose_layout
puts 'ssssssssssssss'
if params[:action] == "new_index"
  'application'
else
  'admin'
end
end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def index
   @latest_testimonial = Testimonials.last
  end
  def sharepoint_services
   @latest_testimonial = Testimonials.last
  end
  def webapplication_development
   @latest_testimonial = Testimonials.last
  end
  def product_development
   @latest_testimonial = Testimonials.last
  end
  def opensource_customizations
   @latest_testimonial = Testimonials.last
  end
  def staff_augmentation
   @latest_testimonial = Testimonials.last
  end
  def reselling
   @latest_testimonial = Testimonials.last
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def index
    @latest_testimonial = Testimonials.last
  end
  def content_manage
    @latest_testimonial = Testimonials.last
  end
  def test_genius
    @latest_testimonial = Testimonials.last
  end
  def equilab
    @latest_testimonial = Testimonials.last
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/aboutus/_form.html.erb
<h4>Relevant Links</h4>
<%= link_to 'Why Indigenius' , aboutus_why_indigenius_path %><br />
<%= link_to 'Our Story' , aboutus_our_story_path %><br />
<%= link_to 'Clientele' , aboutus_clientele_path %><br />
<%= link_to 'Our Commitment to Clients' , aboutus_commitment_path %>

app/views/aboutus/clientele.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'aboutus.png' , :alt => 'About Indigenius' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
Indigenius has an enviable customer base from a variety of industries. Our customer centric practices have bestowed us recurring business from the existing clients. The following is the partial client list of Indigenius IT Solutions
<br /><br />
Napier Healthcare (MS SharePoint Portal) | Napier Intranet Portal is meant to be the primary collaboration and content sharing mechanism with the following features:<br /><br />
. Rich Enterprise business collaboration platform for effective communication and collaboration.<br />
. A platform for sharing information and learning.<br />
. Centralized repository for Document Management with versioning control.</br />
. Enterprise Search.<br />
. Rich Team Sites for HR, Marketing, Finance, Admin, Quality, IIS, Audit, Sales and Pre Sales.<br />
. Customized Work flows for HR Activities, Marketing Business processes, Sales and Pre Sales Workflows,<br />
. Auditing process automation etc.<br />
. Personalized “My Site” to each and every employee.<br />
. Access Control to Users and Groups at different levels.<br />
. End-end workflow implementation & customization.<br />
</div>
<div id="container-right">
<%= render 'form' %>
<%= render 'home/form' %>
</div></div>

app/views/aboutus/commitment.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'aboutus.png' , :alt => 'About Indigenius' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
Indigenius Solutions adhere to the following commitments:<br /><br />

<h3>Delivering high quality value</h3>
A lot more can be achieved within IT budgets as a result of Indigenius’ extremely competitive cost structure, made possible through its resource center in India. This cost advantage with an effective mixture of quality delivers value to our clients and their business.<br /><br />

<h3>Delivering value to you</h3>
IndiGenius ensures that the solution perfectly complements existing business strategies, practices, structures and vision, thereby ensuring that you receive solutions that are tailor made for your business scenario.<br /><br />

<h3>Delivering value through processes</h3>
IndiGenius has a management team with a vision to be an ISO 9001 company to clearly define the processes and follow them stringently for the advantage of our clients. A CMM certification lined up in the near future, IndiGenius’ systems and processes are based on the day to day experiences and involvement of each and everyone of the team and continuously evolving with every engagement.
</div>
<div id="container-right">
<%= render 'form' %>
<%= render 'home/form' %>
</div></div>

app/views/aboutus/index.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'aboutus.png' , :alt => 'About Indigenius' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
IndiGenius Solutions is here to provide you with an effective web strategy for your organization, to partner with you in understanding your industry-business scenario, suggest innovative solutions to your organization and most importantly e-enable your enterprise with your partners globally.
</div>
<div id="container-right">
<%= render 'form' %>
<%= render 'home/form' %>
</div></div>

app/views/aboutus/our_story.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'aboutus.png' , :alt => 'About Indigenius' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
<h4>Innovative</h4>
we are Innovative in our ideas and solutions to our clients. We at IndiGenius imbibe innovativeness in every realm of life. Innovation – the successful exploitation of new ideas – incorporating new technologies, design and best practice is the key business process that enables IndiGenius to compete effectively in the global environment.
<br /><br />
<h4>Genuine</h4>
we are genuine in providing the best solutions that fits the customer needs and enhance the value of their business. We believe in studying the customers' business, understand their requirement, suggest an effective model and implement the solution so as to fulfill their growth objective. This genuineness made us much closer to the hearts of our customers.
<br /><br />
<h4>Simple</h4>
we are simple in our practices. We follow the simplest norms of business to add value proposition to the solutions we provide. IndiGenius is an 'act simple and smart' solution provider
</div>
<div id="container-right">
<%= render 'form' %>
<%= render 'home/form' %>
</div></div>

app/views/aboutus/why_indigenius.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'aboutus.png' , :alt => 'About Indigenius' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
<h4>IndiGenius’ Team believes in the following –</h4>
“This above all: to thine own self be true; and it must follow, as the night the day; Thou canst not then be false to any man” - William Shakespeare<br /><br />

We, at IndiGenius, thoroughly understand customer’s business needs and convert them into the web arena using the latest technology platforms. Our solutions fit in organizations’ growth plans and help our clients achieve their goals and targets. IndiGenius helps customers in deciding what is best, given organization’s constraints on cost, scope and schedules. Our solutions help our Customers stay ahead - be it with respect to competition or quality of internal service delivery. All our existing clients stand testimonial for our passionate efforts towards their satisfaction.
</div>
<div id="container-right">
<%= render 'form' %>
<%= render 'home/form' %>
</div></div>

app/views/dashboard/index.html.erb
<div id='content'>
  <div id='content-inner'>
This is my Dashboard path
</div></div>

app/views/home/_form.html.erb
<h4>A Word From Our Client</h4> 
<%= @latest_testimonial.clientword %>
<%= render 'layouts/mail_form' %>

app/views/home/about_us.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'aboutus.png' , :alt => 'About Indigenius' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
Indigenius IT Solutions Pvt Ltd is a young and dynamic software development company based out of Hyderabad, India.Indigenius specializes in the implementation of MS SharePoint applications enabling enterprise wide collaboration and communication, web application development using open-source frameworks like Ruby on Rails, Outsourced product development, and work flow based enterprise applications for small and medium industries. Managed by experienced industry professionals, Indigenius has emerged as one of the trusted IT partner providing software solutions; a testimony to this is the long and the impressive list of clientele.</div>
<div id="container-right">
<%= render 'form' %>
</div>
</div>

app/views/home/careers.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'careers.png' , :alt => 'Indigenius Careers' , :title => 'Indigenius' %>
  </div>
</div>
<div id='container'>
  <div id='container-left'>
 The value systems with in our team, ensures everyone to feel at home, contribute to each and everyone’s growth, enjoyment in the team work without forgetting the passion towards work.

Interested to be a part of this ever evolving creative team?
Please send us your profile to info@indigenius.com with "Careers" in the subject line.
We are sure to encourage you.
  </div>
<div id="container-right">
<%= render 'form' %></div></div>

app/views/home/contact_us.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'careers.png' , :alt => 'Indigenius Careers' , :title => 'Indigenius' %>
  </div>
</div>
<div id='container'>
  <div id='container-left'>
IndiGenius Solutions<br />
Plot No. 844, Flat No. 303, 3rd floor, Srivatsam,<br />
Road No. 44, Jubilee Hills, Hyderabad - 500 033, INDIA<br />
Phone Number : <br />
(+91) 40 64599776<br />
Mobile No : <br />
(+91) 99084 99000<br />
Write us an e-mail at:<br />
info@indigenius.com
</div>
<div id="container-right">
<%= render 'form' %></div>
</div>

app/views/home/disclaimer.html.erb
<div id="banner">
 <div id="banner-inner">
  <%= image_tag 'Disclaimer.png' , :alt => 'Indigenius Disclaimer' , :title => 'Indigenius' %>
 </div>
</div>
<div id="container">
<div id="container-left">
The website is only a conceptual presentation and not a legal offering. The developer reserves the right for any deletion / addition in plans / specifications and elevations.
Details are subject to change and all optional amenities other than the standard specifications are at extra cost.
<h3 style="color:#8B0A50">WARNING:</h3>
Computer viruses can be transmitted via email. The recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. </div>
</div>
<div id="container-right">
<%= render 'form' %></div></div>

app/views/home/feedback.html.erb
<div id="banner">
<div id="banner-inner">
<%= image_tag 'services.png' %>
</div></div>
<div id="container">
<div id="container-left">
<h2 align="center">Thank You</h2></div>
<div id="container-right">
<%= render 'form' %></div>
</div>

app/views/home/index.html.erb
<div id='banner'>
  <div id='banner-inner' style="margin: 32px 40px 1px;">
      <%#= image_tag 'home.png' , :alt => 'Indigenius Home' , :title => 'Indigenius' %>


<%= javascript_include_tag "jquery-1.6.1.min.js","jquery.nivo.slider.pack.js" %>
<%= stylesheet_link_tag 'default','pascal','orman','nivo-slider' %>
 

 
    <div id="wrapper">
    

        <div class="slider-wrapper theme-default" style="width:90%;">
            <div class="ribbon"></div>
            <div id="slider" class="nivoSlider">
                <img src="/images/enterprise.png" alt="" />
                <img src="/images/consulting.png" alt="" />
                <img src="/images/outsource.png" alt="" />
                <img src="/images/portal.png" alt="" title="#htmlcaption" />
            </div>
            
        </div>

    </div>
    
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>
 




  </div>
</div>
<div id='content'  >
  <div id='content-left'  style="margin: 55px 4px 1px 1px;">
      <h4>Latest Updates</h4> 
       <%= @latest_news.content %>
  </div>
  <div id='content-center' style="margin: 55px 1px 5px 55px;">
      <h4>A Word From Our Client</h4> 
      <%= @latest_testimonial.clientword %>
  </div>
  <div id='content-right' style="margin: 55px 1px 21px 4px;">
     <%= render "layouts/mail_form" %>
  
</div>

</div>

app/views/home/privacy_policy.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'privacy_policy.png' , :alt => 'Indigenius Careers' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
This site contains links to other sites. Text 100 Public Relations. Is not responsible for the privacy practices<br /> or the content of such Web sites.<br />

This site gives users the following options for removing their information from our database to not receive future<br /> communications. <br />
</div>
<div id="container-right">
<%= render 'form' %></div>
</div>

app/views/home/process_email.html.erb
<div id="container">
<div id="container-left">
<h4>Thank u For Contacting Us </h4>
</div></div>

app/views/home/sitemap.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'sitemap.png' , :alt => 'Indigenius Careers' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
<h2>Sitemap Content Here</h2>
</div>
<div id="container-right">
<%= render 'form' %></div>
</div>

app/views/service/_form.html.erb
<div id="container-right">
<h4>Relevant Links</h4>
<%= link_to 'MS SharePoint Services' , service_sharepoint_services_path%><br />
<%= link_to 'Web Application Development' , service_webapplication_development_path%><br />
<%= link_to 'Outsourced Product Development' , service_product_development_path%><br />
<%= link_to 'OpenSource Customizations' , service_opensource_customizations_path %><br />
<%= link_to 'Value-added Staff Augmentation' , service_staff_augmentation_path %><br />
<%= link_to 'Value-added Reselling' , service_reselling_path %><br />
<%= render 'home/form' %>
</div>

app/views/service/index.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'services.png' , :alt => 'Indigenius services' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
IndiGenius offers innovative and simple solutions for your requirements. We constantly experiment with new<br />
technologies to bring the best of the solutions to you.Indigenius IT Solutions Pvt Ltd is a young and dynamic <br />
software development company based out of Hyderabad, India. 
</div>
<%= render 'form' %>
</div>

app/views/service/opensource_customizations.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'services.png' , :alt => 'Indigenius services' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
Indigenius provides custom built applications to clients using popular and tested Open Source Technology stacks. Indigenius extensively works on customizing open source applications to meet clients need. Indigenius performs extensive research to identify the best open source application that suits client’s business needs. 
</div>
<%= render 'form' %>
</div>

app/views/service/product_development.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'services.png' , :alt => 'Indigenius services' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
Indigenius Solutions have developed enterprise grade products for various domains. Most successful products developed by IndiGenius are:
Bullet 	Web-based Assessment Engine (Education & HR Domain)
Bullet 	Biometric Enabled Volunteer Management (Clinical Research)
</div>
<%= render 'form' %>
</div>

app/views/service/reselling.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'services.png' , :alt => 'Indigenius services' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
EMC: Indigenius provides Storage, Security, Virtualisation, Back up & Recovery Solutions from EMC Corporation. We are value added resellers for EMC in India. 
Cisco:  Indigenius provides networking solutions from Cisco to clients in India.   
</div>
<%= render 'form' %>
</div>

app/views/service/sharepoint_services.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'services.png' , :alt => 'Indigenius services' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
MS SharePoint is the fastest growing product from Microsoft stable. It holds leadership position in the multiple<br /> workloads it offers under one umbrella. Following the success of SharePoint 2007, Microsoft released SharePoint<br />
 2010 with a host of functionalities that makes it compelling for enterprise-wide adoption. 
</div>
<%= render 'form' %>
</div>

app/views/service/staff_augmentation.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'services.png' , :alt => 'Indigenius services' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
Team Indigenius has many man-years of experience in providing contingent workforce management services and exceeding client expectations through highly effective processes for recruiting, screening, testing, and consultant management. Over the years, Indigenius team has formulated strategies, processes - enabling the sourcing engine to mature into one of the reliable partner. 
</div>
<%= render 'form' %>
</div>

app/views/service/webapplication_development.html.erb
<div id='banner'>
  <div id='banner-inner'>
      <%= image_tag 'services.png' , :alt => 'Indigenius services' , :title => 'Indigenius' %>
  </div>
</div>
<div id="container">
<div id="container-left">
Indigenius undertakes web portal design and development services which includes e-strategy consulting and technology roadmap creation. Indigenius develops robust, smart and efficient web application in Ruby on Rails
</div>
<%= render 'form' %>
</div>