config/routes.rb
Indigenius::Application.routes.draw do
  get "aboutus/index"

  get "aboutus/why_indigenius"

  get "aboutus/our_story"
 
  get "aboutus/clientele"

  get "aboutus/commitment"

  get "casestudies/index"

  get "casestudies/online_exam_framework"

  get "solutions/index"

  get "solutions/content_manage"
 
  get "solutions/test_genius"
  
  get "solutions/equilab"

  get "technologies/index"

  get "service/index"

  get "service/sharepoint_services"

  get "service/webapplication_development"

  get "service/product_development"

  get "service/opensource_customizations"

  get "service/staff_augmentation"

  get "service/reselling"

  resources :testimonials

  resources :news do
    get 'new_index' , :on => :collection 
  end

  get "dashboard/index"

resources :administrator

 resources :login do
 get 'logout' , :on => :collection
end
   get "home/index"
 
   get "home/careers"

   get "home/contact_us"

   get "home/sitemap"

   get "home/disclaimer"

   get "home/privacy_policy"

   get "home/about_us"

   get "home/feedback"

   post "home/process_email"

   root :to => "home#index"

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/testimonials.rb
class Testimonials < ActiveRecord::Base
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
  def index
    @latest_testimonial = Testimonials.last
  end
  def why_indigenius
    @latest_testimonial = Testimonials.last
  end
  def our_story
    @latest_testimonial = Testimonials.last
  end
  def clientele
    @latest_testimonial = Testimonials.last
  end
  def commitment
    @latest_testimonial = Testimonials.last
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @latest_news = News.last
     @latest_testimonial = Testimonials.last
  end 
  def careers
    @latest_testimonial = Testimonials.last
  end
  def contact_us
    @latest_testimonial = Testimonials.last
  end
  def sitemap
     @latest_testimonial = Testimonials.last
  end
  def disclaimer
     @latest_testimonial = Testimonials.last
  end
  def privacy_policy
     @latest_testimonial = Testimonials.last
  end
  def about_us
     @latest_testimonial = Testimonials.last
  end
  def feedback 
     @latest_testimonial = Testimonials.last
  end

  def process_email
   # puts '111111111111111111111111', params[:email]
    UserMailer.send_email(params[:email]).deliver
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  layout nil 

 def new    
    @administrator = Administrator.new
  end

 def create
 
   @administrator = Administrator.new(params[:administrator])
   @admin = Administrator.find_all_by_username(@administrator.username)
   if(!@admin.blank? && @admin.first.password.eql?(@administrator.password))
    session[:admin] = @admin.first.id
    flash[:notice] = "Logged in Successfully"
    redirect_to dashboard_index_path
   else
    flash[:error] = "Failed to login"
    redirect_to new_login_path
   end

  end


  def logout   
   session[:admin] = nil if session[:admin]   
   redirect_to new_login_path
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
 
 before_filter :check_session , :except => :new_index
layout :choose_layout
# layout 'admin' , :except => :new_index

#layout 'application' , :only => :new_index

  def index
    @news=News.all
    #respond_to do |format|
     # format.html 
  #end
  end

  def new
    @news = News.new
    #respond_to do |format|
     # format.html 
  #end
  end

  def create
    @news = News.new(params[:news])
    respond_to do |format|
      if @news.save
        format.html { redirect_to(@news, :notice => 'Update was successfully created.') }
       else
        format.html { render :action => "new" }
     end
  end
  end

  def edit
   @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to(news_index_path, :notice => 'Update was successfully updated.') }
     else
        format.html { render :action => "edit" }
    end
  end
end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    #respond_to do |format|
     # format.html { redirect_to(news_index_path) }   
  #end
end

  def show
   @news = News.find(params[:id])
   #respond_to do |format|
    #  format.html
 #end
 end
 def new_index
   @latest_testimonial = Testimonials.last
   @latest_news = News.all
 end
private
def choose_layout
puts 'ssssssssssssss'
if params[:action] == "new_index"
  'application'
else
  'admin'
end
end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def index
   @latest_testimonial = Testimonials.last
  end
  def sharepoint_services
   @latest_testimonial = Testimonials.last
  end
  def webapplication_development
   @latest_testimonial = Testimonials.last
  end
  def product_development
   @latest_testimonial = Testimonials.last
  end
  def opensource_customizations
   @latest_testimonial = Testimonials.last
  end
  def staff_augmentation
   @latest_testimonial = Testimonials.last
  end
  def reselling
   @latest_testimonial = Testimonials.last
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/administrator_helper.rb
module AdministratorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/layouts/_image_slideshow.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<html lang="en">
<head>
    <title>Nivo Slider Demo</title>
    <link rel="stylesheet" href="../themes/default/default.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="../themes/pascal/pascal.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="../themes/orman/orman.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="../nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="style.css" type="text/css" media="screen" />
</head>
<body>
    <div id="wrapper">
    
        <a href="http://dev7studios.com" id="dev7link" title="Go to dev7studios">dev7studios</a>

        <div class="slider-wrapper theme-default">
            <div class="ribbon"></div>
            <div id="slider" class="nivoSlider">
                <img src="images/toystory.jpg" alt="" />
                <a href="http://dev7studios.com"><img src="images/up.jpg" alt="" title="This is an example of a caption" /></a>
                <img src="images/walle.jpg" alt="" />
                <img src="images/nemo.jpg" alt="" title="#htmlcaption" />
            </div>
            <div id="htmlcaption" class="nivo-html-caption">
                <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
            </div>
        </div>

    </div>
    <script type="text/javascript" src="scripts/jquery-1.6.1.min.js"></script>
    <script type="text/javascript" src="../jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>
</body>
</html>

app/views/layouts/_mail_form.html.erb
 <h4>Want us to get in touch</h4>
Please leave your contact details</br> and we will get back to you soon!

<%= form_tag("/home/process_email" , :method => "post") do %>
  
  <%= text_field_tag(:email) %>
  <%= submit_tag("Go") %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Indigenius</title>
<%= stylesheet_link_tag 'admin.css' %>
<div id='header'>
  <div id='header-inner'>
   <% flash.each do |key, msg| %>
     <%=content_tag :div, msg, :id =>"flash_#{key}" %>
<% end %>
  </div>
</div>
</head>
<body bgcolor="#00EEEE">
<div id='menu'>
  <div id='menu-inner'>
    <%= link_to 'Create News item', new_news_path %> |
<%= link_to 'Create Testimonial', new_testimonial_path %> |
<%= link_to 'Logout' , logout_login_index_path %> <br />
  </div>
</div>
<%= yield %>
</div> 
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<body bgcolor="#03A89E">
<%= stylesheet_link_tag 'indigenius.css' %>
<div id='header'>
  <div id='header-left'>
      <%= image_tag 'logo.png' , :alt => 'Indigenius logo' , :title => 'Indigenius' %>
  </div>
  <div id='header-right'>
      <%= link_to 'Home' , home_index_path %>   |   <%= link_to 'News&Updates' , new_index_news_index_path %>    |    <%= link_to 'Careers' , home_careers_path %>    |    <%= link_to 'Contact Us' , home_contact_us_path %>  |   <%= link_to 'Login' , new_login_path %>
  </div>
</div>
<div>
</div>
<div id='menu'>
  <div id='menu-inner'>
      <%= link_to 'Services' , service_index_path %> | <%= link_to 'Technologies' , technologies_index_path%> | <%= link_to 'Solutions' , solutions_index_path %> | <%= link_to 'CaseStudies' , casestudies_index_path %> | <%= link_to 'About Us' , aboutus_index_path %>
  </div>
</div>

<% flash.each do |key, msg| %>
     <%=content_tag :div, msg, :id =>"flash_#{key}" %>
<% end %>

<%= yield %>
<br /><br /><br />
<div id='footer'>
  <div id='footer-left'>
      Copyright © 2011-12 Indigenius IT Solutions Private Limited. All rights reserved.
  </div>
  <div id='footer-right'>
      <%= link_to 'Feedback' , home_feedback_path %>  |  <%= link_to 'SiteMap' , home_sitemap_path %>  |  <%= link_to 'Disclaimer' , home_disclaimer_path %> |  <%= link_to 'Privacy Policy' , home_privacy_policy_path %>  |  <%= link_to 'Contact Us' , home_contact_us_path %> 
  </div>
</div> 
</body>
</html>